version: '3'

services:
  nginx:
    image: nginx:1.28.0-alpine
    container_name: resume-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../logs:/var/log/nginx
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge 