version: '3'

services:
  redis:
    image: redis:8.0.0-alpine
    container_name: resume-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 100mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    networks:
      - resume-network

volumes:
  redis-data:

networks:
  resume-network:
    driver: bridge
