version: '3'

services:
  app-green:
    image: rana718/resume-backend:latest
    container_name: aicvbuilder-backend-green
    pull_policy: always
    restart: always
    ports:
      - "8002:8000"
    env_file:
      - ../envs.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge
