"""add paymnts limtations

Revision ID: 15f84c9a9af9
Revises: b6e5022f43a2
Create Date: 2025-10-13 15:01:32.498088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f84c9a9af9'
down_revision: Union[str, Sequence[str], None] = 'b6e5022f43a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('download_limit', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('downloads_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'downloads_used')
    op.drop_column('plans', 'download_limit')
    # ### end Alembic commands ###
