"""remove the logs && add the role

Revision ID: 6e2a49bf1afa
Revises: 26397551ebcf
Create Date: 2025-09-04 20:42:05.389286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e2a49bf1afa'
down_revision: Union[str, Sequence[str], None] = '26397551ebcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if activity_logs table exists before trying to drop it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    if 'activity_logs' in inspector.get_table_names():
        # Drop activity_logs table if it exists
        op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
        op.drop_table('activity_logs')
    
    # Add role columns to users table
    op.add_column('users', sa.Column('isSuperAdmin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    
    # Note: Skipping foreign key constraint modifications as they may already be in the correct state
    # The tables should already have the proper foreign key constraints from previous migrations
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove role columns from users table
    op.drop_column('users', 'isAdmin')
    op.drop_column('users', 'isSuperAdmin')
    
    # Recreate activity_logs table
    op.create_table('activity_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    
    # Note: Skipping foreign key constraint modifications as they should remain as they are
    # ### end Alembic commands ###
