"""remove the github and linkedin and manully

Revision ID: 7ffc1cbf2e76
Revises: 9f9e8cbc113f
Create Date: 2025-09-09 15:17:38.731645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ffc1cbf2e76'
down_revision: Union[str, Sequence[str], None] = '9f9e8cbc113f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('socail_links', sa.JSON(), nullable=True))
    op.drop_column('resumes', 'linkedin_url')
    op.drop_column('resumes', 'github_url')
    op.drop_column('resumes', 'portfolio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('portfolio_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('resumes', sa.Column('github_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('resumes', sa.Column('linkedin_url', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('resumes', 'socail_links')
    # ### end Alembic commands ###
