"""add the templates id

Revision ID: 814d62809239
Revises: 6da93cdb43e5
Create Date: 2025-09-03 02:28:50.412359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814d62809239'
down_revision: Union[str, Sequence[str], None] = '6da93cdb43e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('template_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cover_letters', 'template_id')
    # ### end Alembic commands ###
