"""add the user table

Revision ID: 85a989d22405
Revises: 06342d79ef0b
Create Date: 2025-08-28 16:26:52.871102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85a989d22405'
down_revision: Union[str, Sequence[str], None] = '06342d79ef0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.String(length=255), nullable=True))
    op.drop_column('users', 'projects')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'summary')
    op.drop_column('users', 'template_id')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'languages')
    op.drop_column('users', 'certifications')
    op.drop_column('users', 'education')
    op.drop_column('users', 'address')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'theme_color')
    op.drop_column('users', 'portfolio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('portfolio_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('users', sa.Column('theme_color', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('experience', mysql.JSON(), nullable=True))
    op.add_column('users', sa.Column('skills', mysql.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('job_title', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('users', sa.Column('address', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('education', mysql.JSON(), nullable=True))
    op.add_column('users', sa.Column('certifications', mysql.JSON(), nullable=True))
    op.add_column('users', sa.Column('languages', mysql.JSON(), nullable=True))
    op.add_column('users', sa.Column('github_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('users', sa.Column('template_id', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('summary', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('users', sa.Column('projects', mysql.JSON(), nullable=True))
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
