"""fix the scheme

Revision ID: 965a4ce8ac95
Revises: 814d62809239
Create Date: 2025-09-03 06:24:02.265598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965a4ce8ac95'
down_revision: Union[str, Sequence[str], None] = '814d62809239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('shareable_uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_cover_letters_shareable_uuid'), 'cover_letters', ['shareable_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cover_letters_shareable_uuid'), table_name='cover_letters')
    op.drop_column('cover_letters', 'shareable_uuid')
    # ### end Alembic commands ###
