"""add the images

Revision ID: 9e5f69e6079b
Revises: a05e51e23622
Create Date: 2025-08-29 01:49:27.386757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e5f69e6079b'
down_revision: Union[str, Sequence[str], None] = 'a05e51e23622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('github_id', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'image_url')
    op.drop_column('resumes', 'image_url')
    op.drop_column('resumes', 'email')
    # ### end Alembic commands ###
