"""add the address

Revision ID: a05e51e23622
Revises: 85a989d22405
Create Date: 2025-08-28 16:30:15.755568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a05e51e23622'
down_revision: Union[str, Sequence[str], None] = '85a989d22405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('resumes', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('resumes', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('resumes', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('resumes', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('resumes', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.drop_column('users', 'name')
    op.drop_column('users', 'state')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'country')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('postal_code', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('state', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('resumes', 'postal_code')
    op.drop_column('resumes', 'country')
    op.drop_column('resumes', 'state')
    op.drop_column('resumes', 'city')
    op.drop_column('resumes', 'phone')
    op.drop_column('resumes', 'name')
    # ### end Alembic commands ###
