name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: rana718/resume-backend:latest

      - name: Deploy to VPS
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          password: ${{ vars.VPS_PASS }}
          script: |
            cd /home/aydrana/deployment
            git pull
            echo "Pulling latest code..."
            cd /home/aydrana/deployment/cvbuilder/deployment
            chmod +x deploy.sh
            ./deploy.sh
            echo "Deployment script executed successfully."
