name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: rana718/resume-backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /home/aydrana/deploymen
            git pull
            echo "Pulling code..."
            cd /home/aydrana/deploymen/cvbuilder/deployment
            chmod +x deploy.sh
            ./deploy.sh
            echo "Deployment script executed."
            
